"""Controlled values for the governance tables. CHECK constraints in ddl.py are generated from these."""

# Unity Catalog object types the scan covers, and the ALTER keyword used to tag each one.
TABLE_TYPE_ALTER = {
    "MANAGED": "TABLE",
    "EXTERNAL": "TABLE",
    "MATERIALIZED_VIEW": "MATERIALIZED VIEW",
    "STREAMING_TABLE": "STREAMING TABLE",
}
SCANNED_TABLE_TYPES = tuple(TABLE_TYPE_ALTER)

# Pipeline-internal tables live beside the datasets they back and carry no business columns.
EXCLUDED_TABLE_PREFIXES = ("__materialization_", "event_log_")

ENVIRONMENTS = ("dev", "test", "prod")

# Recertification interval, in months, per risk tier.
RISK_TIER_MONTHS = {"HIGH": 3, "STANDARD": 6}

BATCH_OPEN = "OPEN"
BATCH_CLOSED = "CLOSED"
BATCH_STATUSES = (BATCH_OPEN, BATCH_CLOSED)

# Issue types, in precedence order: when several apply, the first one wins.
CORRECTION_REQUESTED = "CORRECTION_REQUESTED"
INVALID_TAG_VALUE = "INVALID_TAG_VALUE"
STALE_PHI_REVIEW = "STALE_PHI_REVIEW"
STALE_NON_PHI_ATTESTATION = "STALE_NON_PHI_ATTESTATION"
ORPHANED_TAG = "ORPHANED_TAG"
RECERTIFICATION_DUE = "RECERTIFICATION_DUE"
MISSING_CLASSIFICATION = "MISSING_CLASSIFICATION"
ISSUE_TYPES = (
    CORRECTION_REQUESTED,
    INVALID_TAG_VALUE,
    STALE_PHI_REVIEW,
    STALE_NON_PHI_ATTESTATION,
    ORPHANED_TAG,
    RECERTIFICATION_DUE,
    MISSING_CLASSIFICATION,
)

# Review item statuses. A submitted decision waits in classification_decision_submission until
# ingestion validates it, so the item keeps its status until then.
PENDING_STEWARD_REVIEW = "PENDING_STEWARD_REVIEW"
NEEDS_PRIVACY_REVIEW = "NEEDS_PRIVACY_REVIEW"
VALIDATION_FAILED = "VALIDATION_FAILED"
PLANNED = "PLANNED"
APPLICATION_IN_PROGRESS = "APPLICATION_IN_PROGRESS"
TAG_VERIFIED = "TAG_VERIFIED"
ATTESTED_NOT_PHI = "ATTESTED_NOT_PHI"
APPLICATION_FAILED = "APPLICATION_FAILED"
CLOSED_NO_ACTION = "CLOSED_NO_ACTION"
ITEM_STATUSES = (
    PENDING_STEWARD_REVIEW,
    NEEDS_PRIVACY_REVIEW,
    VALIDATION_FAILED,
    PLANNED,
    APPLICATION_IN_PROGRESS,
    TAG_VERIFIED,
    ATTESTED_NOT_PHI,
    APPLICATION_FAILED,
    CLOSED_NO_ACTION,
)
TERMINAL_ITEM_STATUSES = (TAG_VERIFIED, ATTESTED_NOT_PHI, CLOSED_NO_ACTION)
# Statuses in which a submitted decision is acted on.
DECIDABLE_ITEM_STATUSES = (PENDING_STEWARD_REVIEW, VALIDATION_FAILED, NEEDS_PRIVACY_REVIEW)

# Steward decisions.
APPROVE_SUGGESTION = "APPROVE_SUGGESTION"
CORRECT_CLASSIFICATION = "CORRECT_CLASSIFICATION"
CONFIRM_NOT_PHI = "CONFIRM_NOT_PHI"
REQUEST_PRIVACY_REVIEW = "REQUEST_PRIVACY_REVIEW"
DECISIONS = (APPROVE_SUGGESTION, CORRECT_CLASSIFICATION, CONFIRM_NOT_PHI, REQUEST_PRIVACY_REVIEW)

SET_PHI_TAG = "SET_PHI_TAG"
REMOVE_PHI_TAG = "REMOVE_PHI_TAG"
ACTION_TYPES = (SET_PHI_TAG, REMOVE_PHI_TAG)

CONFIRMED_NOT_PHI = "CONFIRMED_NOT_PHI"
ATTESTATION_TYPES = (CONFIRMED_NOT_PHI,)

# Submissions written by the review app.
SUBMISSION_DECISION = "DECISION"
SUBMISSION_ASSIGNMENT = "ASSIGNMENT"
SUBMISSION_TYPES = (SUBMISSION_DECISION, SUBMISSION_ASSIGNMENT)

ROLE_ASSIGNED_STEWARD = "ASSIGNED_STEWARD"
ROLE_STEWARD_GROUP_MEMBER = "STEWARD_GROUP_MEMBER"
ROLE_DATA_GOVERNANCE = "DATA_GOVERNANCE"
SUBMITTER_ROLES = (ROLE_ASSIGNED_STEWARD, ROLE_STEWARD_GROUP_MEMBER, ROLE_DATA_GOVERNANCE)

# Event types.
BATCH_CREATED = "BATCH_CREATED"
ITEM_OPENED = "ITEM_OPENED"
ITEM_CLOSED = "ITEM_CLOSED"
SUBMISSION_INGESTED = "SUBMISSION_INGESTED"
STEWARD_ASSIGNED = "STEWARD_ASSIGNED"
EVT_DECISION_RECEIVED = "DECISION_RECEIVED"
EVT_VALIDATION_FAILED = "VALIDATION_FAILED"
CHANGE_IGNORED_ALREADY_RESOLVED = "CHANGE_IGNORED_ALREADY_RESOLVED"
PRIVACY_REVIEW_REQUESTED = "PRIVACY_REVIEW_REQUESTED"
PLAN_CREATED = "PLAN_CREATED"
ATTESTATION_RECORDED = "ATTESTATION_RECORDED"
EVT_TAG_VERIFIED = "TAG_VERIFIED"
TAG_REMOVED = "TAG_REMOVED"
EVT_APPLICATION_FAILED = "APPLICATION_FAILED"
BATCH_CLOSED_EVT = "BATCH_CLOSED"
BATCH_ERROR = "BATCH_ERROR"
EVENT_TYPES = (
    BATCH_CREATED,
    ITEM_OPENED,
    ITEM_CLOSED,
    SUBMISSION_INGESTED,
    STEWARD_ASSIGNED,
    EVT_DECISION_RECEIVED,
    EVT_VALIDATION_FAILED,
    CHANGE_IGNORED_ALREADY_RESOLVED,
    PRIVACY_REVIEW_REQUESTED,
    PLAN_CREATED,
    ATTESTATION_RECORDED,
    EVT_TAG_VERIFIED,
    TAG_REMOVED,
    EVT_APPLICATION_FAILED,
    BATCH_CLOSED_EVT,
    BATCH_ERROR,
)

MANUAL = "MANUAL"

# Steward review window when a scan creates a batch.
REVIEW_DUE_DAYS = 14
